In [3]:
#QR decomposition 
#Gyanesh Kuamr Pandey 
#Program to solve system of linear equation Ax=b using QR decompostion. Input for the program Q and R and b
#numpy.linalg.qr linalg.qr(a, mode='reduced')[source] Compute the qr factorization of a matrix.
#Factor the matrix a as qr, where q is orthonormal and r is upper-triangular.
#It can use for reatgaualr matrix 

import scipy.linalg as linalg
import numpy as np

# We can pass A mxn matrix #
A = np.array([[2., 1., 1.],[1., 3., 2.],[1., 0., 0]])
#A = np.array([[2., 1.],[1., 3.],[1., 0.]])

B = np.array([4., 5.,8.])

print('This system of linear equations')
print('Given Matrix -A=')
print(A)

print('Given Matrix B=')
print(B)



Q, R = linalg.qr(A) # QR decomposition with qr function
print('where Q is an orthogonal matrix = ')
print(Q)
print('R is an upper triangular matrix')
print(R)

#Let assume & check if A=QR=B
C=Q.dot(R)
print('#Let assume & check if A=QR=B')
print(C)


y = np.dot(Q.T, B) # Let y=Q'.B using matrix multiplication
x = linalg.solve(R, y) # Solve Rx=y

print('Use the solve function to solve the system of linear equations -Final Result')
print (x)



This system of linear equations
Given Matrix -A=
[[2. 1. 1.]
 [1. 3. 2.]
 [1. 0. 0.]]
Given Matrix B=
[4. 5. 8.]
where Q is an orthogonal matrix = 
[[-0.81649658  0.27602622 -0.50709255]
 [-0.40824829 -0.89708523  0.16903085]
 [-0.40824829  0.34503278  0.84515425]]
R is an upper triangular matrix
[[-2.44948974 -2.04124145 -1.63299316]
 [ 0.         -2.41522946 -1.51814423]
 [ 0.          0.         -0.16903085]]
#Let assume & check if A=QR=B
[[ 2.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  1.09812324e-16 -2.08416416e-17]]
Use the solve function to solve the system of linear equations -Final Result
[  8.  21. -33.]
